language: go

before_install:
  - "cd $TRAVIS_BUILD_DIR && chmod +x ./make.bash && ./make.bash version $TRAVIS_BUILD_DIR"

script:
  - go test -v ./...

after_failure:
  - "cd $TRAVIS_BUILD_DIR && chmod +x ./make.bash && ./make.bash build_failed"

